// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entity
{
    public partial class MarcaVehiculoEntity:EN
    {
        public int? MarcaVehiculoId { get; set; }
        public double Descripcion { get; set; }
        
    }
}